### ISSUE TITLE
Debugging the Node Launcher on macOS

### ISSUE THREAD

**Issue by Jonbros01** [PierreRochard/node-launcher#140]
Exception: [Errno 2] No such file or directory: '/support/signature/loader.py'
Traceback (most recent call last):
  File "pyscript", line 23, in bootstrap
FileNotFoundError: [Errno 2] No such file or directory: '/support/signature/loader.py'
AttributeError: module 'signature_loader' has no attribute 'pyside_type_init'
Traceback (most recent call last):
  File "run.py", line 10, in <module>
  File "node_launcher/gui/main_widget.py", line 36, in __init__
  File "node_launcher/gui/network_buttons/network_widget.py", line 20, in __init__
  File "node_launcher/node_set/node_set.py", line 32, in __init__
  File "node_launcher/node_set/lnd.py", line 68, in __init__
  File "node_launcher/services/configuration_file.py", line 41, in __getitem__
Exception: Multiple occurrences of listen in /Users/jonathanbrosseau/Library/Application Support/Lnd/lnd.conf
[3607] Failed to execute script run

**Comment by PierreRochard** [comment]
@Jonbros01 hmm, try opening `/Users/jonathanbrosseau/Library/Application Support/Lnd/lnd.conf` and see if there are two `listen=` lines

**Comment by Jonbros01** [comment]
Yes I got 3 listen lines…

listen=0.0.0.0:9737
listen=127.0.0.1:9737
listen=192.168.0.120:9737

**Comment by Jonbros01** [comment]
Ok now the app is launching but when I try to launch LND I get this error:


Last login: Mon Jan 28 17:51:01 on ttys002

/var/folders/ns/msvmjd891_d33jfsj2dhp91m0000gn/T/tmpphcd8409-lnd.command ; exit;

Jonathans-iMac:~ jonathanbrosseau$ /var/folders/ns/msvmjd891_d33jfsj2dhp91m0000gn/T/tmpphcd8409-lnd.command ; exit;

lookup tcp/9737lnddir=/Users/jonathanbrosseau/Library/Application Support/Lnd/: nodename nor servname provided, or not known

logout

Saving session...

...copying shared history...

...saving history...truncating history files...

...completed.

**Comment by PierreRochard** [comment]
Very odd, try clicking the `Reset TLS` button in `Advanced...` and reboot your computer

**Comment by Jonbros01** [comment]
No dosent change anything same issue
