### ISSUE TITLE
Keyring backend not available

### ISSUE THREAD

**Issue by PierreRochard** [PierreRochard/node-launcher#39]
![image](https://user-images.githubusercontent.com/6299681/49487594-1aa5b500-f811-11e8-9055-cb1d0547ab60.png)

**Comment by PierreRochard** [comment]
![image](https://user-images.githubusercontent.com/6299681/49524530-f03c1200-f879-11e8-83cd-5a1cafa5e5ff.png)

**Comment by PierreRochard** [comment]
This is happening on macOS too, but only in the build

```
Traceback (most recent call last):
  File "node_launcher/gui/network_group_box.py", line 183, in create_wallet
  File "keyring/core.py", line 64, in set_password
  File "keyring/backends/fail.py", line 23, in get_password
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.

```

Prioritizing a fix now
