### ISSUE TITLE
win32cred not defined

### ISSUE THREAD

**Issue by kdim218** [PierreRochard/node-launcher#52]
during LND wallet creation:

Traceback (most recent call last):
  File "lib\site-packages\keyring\backends\Windows.py", line 75, in _get_password
NameError: name 'win32cred' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "node_launcher\gui\network_buttons\lnd_wallet_layout.py", line 98, in create_wallet
  File "lib\site-packages\keyring\backends\Windows.py", line 87, in set_password
  File "lib\site-packages\keyring\backends\Windows.py", line 79, in _get_password
NameError: name 'pywintypes' is not defined

**Comment by PierreRochard** [comment]
Thanks, I had a build error for Windows, please download it again!
