### ISSUE TITLE
LND crashes on unlock with "unable to sanity check wallet birthday block"

### ISSUE THREAD

**Issue by stefanwouldgo** [PierreRochard/node-launcher#53]
I have a pruned bitcoind 0.17.0.1 started from the launcher and caught up, then start LND, then unlock a wallet from an older LND version. Then LND crashes with the following logs: 

2018-12-12 13:46:22.144 [INF] LTND: Version: 0.5.1-beta commit=, build=production, logging=default
2018-12-12 13:46:22.145 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2018-12-12 13:46:22.154 [INF] CHDB: Checking for schema update: latest_version=7, db_version=7
2018-12-12 13:46:22.167 [INF] RPCS: password RPC server listening on 127.0.0.1:10011
2018-12-12 13:46:22.168 [INF] RPCS: password gRPC proxy started at 127.0.0.1:8081
2018-12-12 13:46:22.168 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2018-12-12 13:46:39.671 [INF] LNWL: Opened wallet
2018-12-12 13:46:39.750 [INF] LTND: Primary chain is set to: bitcoin
2018-12-12 13:46:39.776 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on tcp://127.0.0.1:18503
2018-12-12 13:46:39.776 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on tcp://127.0.0.1:18502
2018-12-12 13:46:39.777 [INF] LTND: Initializing bitcoind backed fee estimator
2018-12-12 13:46:40.645 [INF] LNWL: The wallet has been unlocked without a time limit
2018-12-12 13:46:40.653 [INF] LTND: LightningWallet opened
2018-12-12 13:46:40.668 [INF] HSWC: Restoring in-memory circuit state from disk
2018-12-12 13:46:40.673 [INF] HSWC: Payment circuits loaded: num_pending=0, num_open=0
2018-12-12 13:46:40.683 [INF] RPCS: RPC server listening on 127.0.0.1:10011
2018-12-12 13:46:40.686 [INF] RPCS: gRPC proxy started at 127.0.0.1:8081
2018-12-12 13:46:40.688 [INF] LTND: Waiting for chain backend to finish sync, start_height=553523
2018-12-12 13:46:45.355 [ERR] LNWL: unable to sanity check wallet birthday block: failed to store sync information 0000000000000000004d81d50fb2e161c606530c80040fa33e1408f8f948239c: failed to fetch block hash for height 513944: block not found
panic: unable to sanity check wallet birthday block: failed to store sync information 0000000000000000004d81d50fb2e161c606530c80040fa33e1408f8f948239c: failed to fetch block hash for height 513944: block not found

goroutine 78 [running]:
github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc000086140)
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/chainntfns.go:111 +0x1145
created by github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
        /Users/roasbeef/gocode/src/github.com/lightningnetwork/lnd/vendor/github.com/btcsuite/btcwallet/wallet/wallet.go:186 +0x15d

**Comment by PierreRochard** [comment]
Ah interesting @stefanwouldgo, thanks for the update!
